services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gateway_db
    ports:
      - "5455:5432"   # 5455 — порт на твоём компьютере, 5432 — внутри контейнера
    volumes:
      - pgdata:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Микросервис billing (раскомментируй, если у тебя есть код)
  # billing:
  #   build: ../billing-service  # Путь к папке с микросервисом
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     SERVICE_TOKEN: your-secret-key
  #   depends_on:
  #     - db

  api-gateway-app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    depends_on:
      - db
      - kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"  # КРИТИЧНО для подключения к внешним сервисам
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/gateway_db
      INTERNAL_SERVICE_KEY: gateway-secret-key-2024
      AUTH_SERVICE_URL: http://host.docker.internal:8000
      # Общий кластер Kafka (если используется в других частях)
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      # Chat Service (точная конфигурация по опыту Billing Service)
      CHAT_SERVICE_URL: http://host.docker.internal:8003
      CHAT_SERVICE_INTERNAL_KEY: chat-service-secret-key
      CHAT_SERVICE_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      CHAT_SERVICE_RESPONSES_TOPIC: chat-service-responses
      CHAT_SERVICE_EVENTS_TOPIC: chat-service-events
      # Дополнительные настройки (как рекомендовал Chat Service)
      CHAT_SERVICE_REQUEST_TIMEOUT: "30000"  # 30 секунд
      CHAT_SERVICE_RETRY_ATTEMPTS: "3"

volumes:
  pgdata: 